### ISSUE TITLE
Config Deep Merging Ignores Null Values

### ISSUE THREAD

**Issue by osterman** [mumoshu/variant2#33]
## what

* We are trying to merge to maps using the `config {...}` construct
* The deep merging works *perfectly* with every value other than `null`
* With `null` the value is just ignored

## expectation

If we merge this map:

```yaml
terraform:
  backend:
    s3:
      encrypt: true
      key: "terraform.tfstate"
      acl: "bucket-owner-full-control"
      region: "us-east-2"
```

with this map:
```yaml
terraform:
  backend:
    s3:
      region: null
```

we should get 

```yaml
terraform:
  backend:
    s3:
      encrypt: true
      key: "terraform.tfstate"
      acl: "bucket-owner-full-control"
      region: null
```
using the following job:

```hcl
job "echo" {
  option "message" {
    type = string
    default = "Hello world!"
  }
  config "test" {
    source file {
      path = "c1.yaml"
    }
    source file {
      path = "c2.yaml"
    }
  }

  exec {
    command = "echo"
    args = [ yamlencode(conf.test) ]
  }
}
```

 but what we actually get is:

```yaml
"terraform":
  "backend":
    "s3":
      "acl": "bucket-owner-full-control"
      "encrypt": true
      "key": "terraform.tfstate"
      "region": "us-east-2"
```
